### ISSUE TITLE
can you give me example to open map code ?

### ISSUE THREAD

**Issue by alonalibarmn** [foobball/AmongUsBot#1]

**Comment by foobball** [comment]
what exactly do you mean?

**Comment by alonalibarmn** [comment]
a!code like this

**Comment by foobball** [comment]
the function that creates the embed with each map can be found from [lines 64-74](https://github.com/foobball/AmongUsBot/blob/61304fb485e766ffa54f730e26815340443eb26b/app.js#L64-L74).
